## 01MIAR - Estructuras de datos, +Pandas



![](img/python_logo.png)




*Alysson Guaman*

**Repositorio:** [Github](https://github.com/a12lj/machine-learning.git)

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'3.0.3'

# Operaciones en pandas

**Búsqueda**

In [3]:
rand_matrix = np.random.randint(6,size=(2,3))
frame = pd.DataFrame(rand_matrix , columns=list('ABC'))
display(frame)

   A  B  C
0  3  1  5
1  4  0  3

In [4]:
# buscando columnas (DataFrame como dic, busca en claves)
'A' in frame

True

In [5]:
# buscando valores
display(frame.isin([3,2]))  # --> mask de respuesta (valores que son 3 o 2)

       A      B      C
0   True  False  False
1  False  False   True

In [7]:
# Contar el número de ocurrencias
print(frame.isin([4]).values.sum())
display(frame.isin([4]))  # devuelve una mask con valores true si el elemento es 4
print(frame.isin([4]).values)
type(frame.isin([4]).values)  # pandas es una capa alrededor de numpy

1

       A      B      C
0  False  False  False
1   True  False  False

[[False False False]
 [ True False False]]

numpy.ndarray

In [8]:
# Cuántos valores son >= 2
mask = frame >= 2
print(mask.values.sum())
display(mask)

4

      A      B     C
0  True  False  True
1  True  False  True

**Ordenación**

In [9]:
from random import shuffle

rand_matrix = np.random.randint(20,size=(5,4))
indices = list(range(5))
shuffle(indices)  # mezcla indices
frame = pd.DataFrame(rand_matrix , columns=list('DACB'), index=indices)
display(frame)

    D  A   C   B
3   1  9   6   9
1   6  9   5   5
4   8  0   2   3
0  16  3   4  13
2  10  9  11   1

In [10]:
# ordenar por índice
display(frame.sort_index(ascending=False))
display(frame)

    D  A   C   B
4   8  0   2   3
3   1  9   6   9
2  10  9  11   1
1   6  9   5   5
0  16  3   4  13

    D  A   C   B
3   1  9   6   9
1   6  9   5   5
4   8  0   2   3
0  16  3   4  13
2  10  9  11   1

In [11]:
#ordenar por columna
display(frame.sort_index(axis=1, ascending=False))

    D   C   B  A
3   1   6   9  9
1   6   5   5  9
4   8   2   3  0
0  16   4  13  3
2  10  11   1  9

In [12]:
# ordenar filas por valor en columna
display(frame.sort_values(by='A', ascending=True))

    D  A   C   B
4   8  0   2   3
0  16  3   4  13
1   6  9   5   5
3   1  9   6   9
2  10  9  11   1

In [13]:
# ordenar columnas por valor en fila
display(frame.sort_values(by=1, axis=1, ascending=True))

    B   C   D  A
3   9   6   1  9
1   5   5   6  9
4   3   2   8  0
0  13   4  16  3
2   1  11  10  9

In [14]:
# ordenar por valor en columna y guardar cambios
frame.sort_values(by='A', ascending=False, inplace=True)
display(frame)

    D  A   C   B
3   1  9   6   9
1   6  9   5   5
2  10  9  11   1
0  16  3   4  13
4   8  0   2   3

**Ranking**

- Construir un ranking de valores

In [15]:
display(frame)

    D  A   C   B
3   1  9   6   9
1   6  9   5   5
2  10  9  11   1
0  16  3   4  13
4   8  0   2   3

In [16]:
display(frame.rank(method='max', axis=1))

     D    A    C    B
3  1.0  4.0  2.0  4.0
1  3.0  4.0  2.0  2.0
2  3.0  2.0  4.0  1.0
0  4.0  1.0  2.0  3.0
4  4.0  1.0  2.0  3.0

In [17]:
# Imprimir, uno a uno, los valores de la columna 'C' de mayor a menor
for x in frame.sort_values(by='C', ascending=False)['C'].values:
    print(x)

11
6
5
4
2

# Operaciones

Operaciones matemáticas entre objetos

In [18]:
matrixA = np.random.randint(100,size=(4,4))
matrixB = np.random.randint(100,size=(4,4))
frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)
display(frameA)
display(frameB)

    0   1   2   3
0  69  59  64   9
1  92  42  55  44
2  51  72  55  59
3  11  10  10  23

    0   1   2   3
0  60  42  25  66
1  29  43  36  80
2  68  33  45  66
3  23  46  35  55

In [19]:
# a través de métodos u operadores
display(frameA + frameB == frameA.add(frameB))
display(frameA + frameB)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

     0    1    2    3
0  129  101   89   75
1  121   85   91  124
2  119  105  100  125
3   34   56   45   78

In [20]:
display(frameB - frameA == frameB.sub(frameA))
display(frameB - frameA)

      0     1     2     3
0  True  True  True  True
1  True  True  True  True
2  True  True  True  True
3  True  True  True  True

    0   1   2   3
0  -9 -17 -39  57
1 -63   1 -19  36
2  17 -39 -10   7
3  12  36  25  32

In [21]:
# si los frames no son iguales, valor por defecto NaN
frameC = pd.DataFrame(np.random.randint(100,size=(3,3)))
display(frameA)
display(frameC)
display(frameC + frameA)

    0   1   2   3
0  69  59  64   9
1  92  42  55  44
2  51  72  55  59
3  11  10  10  23

    0   1   2
0  35  56   7
1  79  81  34
2  81  33   3

       0      1     2   3
0  104.0  115.0  71.0 NaN
1  171.0  123.0  89.0 NaN
2  132.0  105.0  58.0 NaN
3    NaN    NaN   NaN NaN

In [22]:
# se puede especificar el valor por defecto con el argumento fill_value
display(frameA.add(frameC, fill_value=0))

       0      1     2     3
0  104.0  115.0  71.0   9.0
1  171.0  123.0  89.0  44.0
2  132.0  105.0  58.0  59.0
3   11.0   10.0  10.0  23.0

Operadores aritméticos solo válidos en elementos aceptables

In [23]:
frameD = pd.DataFrame({0: ['a','b'],1:['d','f']})
display(frameD)
frameA - frameD

   0  1
0  a  d
1  b  f

TypeError: unsupported operand type(s) for -: 'int' and 'str'

Operaciones entre Series y DataFrames

In [24]:
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(df)

display(df.iloc[0])
display(type(df.iloc[0]))

# uso común, averiguar la diferencia entre una fila y el resto
display(df - df.iloc[0])
display(df.sub(df.iloc[0], axis=1))

# Por columnas cómo se restaría
display(df.sub(df['A'], axis=0))

   A  B  C  D
0  1  7  3  0
1  7  9  8  6
2  4  9  3  0

A    1
B    7
C    3
D    0
Name: 0, dtype: int32

pandas.Series

   A  B  C  D
0  0  0  0  0
1  6  2  5  6
2  3  2  0  0

   A  B  C  D
0  0  0  0  0
1  6  2  5  6
2  3  2  0  0

   A  B  C  D
0  0  6  2 -1
1  0  2  1 -1
2  0  5 -1 -4

pandas se basa en NumPy, np operadores binarios y unarios de son aceptables.

**Unarios**

| Tipo |  Operación | Descripción | 
|---|---|---|
|| `abs` | Valor absoluto de cada elemento |
|| `sqrt` | Raíz cuadrada de cada elemento |
|| `exp` | e^x, siendo x cada elemento |
|Unarios    | `log`, `log10`, `log2` | Logaritmos en distintas bases de cada elemento |
|| `sign` | Retorna el signo de cada elemento (-1 para negativo, 0 o 1 para positivo) |
|| `ceil` | Redondea cada elemento por arriba |
|| `floor` | Redondea cada elemento por abajo |
|| `isnan` | Retorna si cada elemento es NaN |
|| `cos`, `sin`, `tan` | Operaciones trigonométricas en cada elemento |
|| `arccos`, `arcsin`, `arctan` | Inversas de operaciones trigonométricas en cada elemento |

**Binarios**

| Tipo | Operación | Descripción |
|---|---|---|
|| `add` | Suma de dos arrays |
|| `subtract` | Resta de dos arrays |
|Binarios| `multiply` | Multiplicación de dos arrays |
|| `divide` | División de dos arrays |
|| `maximum`, `minimum` | Retorna el valor máximo/mínimo de cada pareja de elementos |
|| `equal`, `not_equal` | Retorna la comparación (igual o no igual) de cada pareja de elementos |
|| `greater`, `greater_equal`, `less`, `less_equal` | Retorna la comparación (>, >=, <, <= respectivamente) de cada pareja de elementos |

Aplicación de funciones a medida con lambda

In [26]:
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1))  # diferencia por fila

   A  B  C  D
0  5  0  3  2
1  2  9  1  7
2  8  1  4  8

0    5
1    8
2    7
dtype: int32

In [27]:
def max_min(x):
    return x.max() - x.min()

print(frame.apply(max_min, axis = 0))  # diferencia por columna

A    6
B    9
C    3
D    6
dtype: int32

In [28]:
# diferencia entre min y max por fila (no columna)
rand_matrix = np.random.randint(10, size=(3, 4))
frame = pd.DataFrame(rand_matrix , columns=list('ABCD'))
display(frame)
print(frame.apply(lambda x : x.max() - x.min(), axis = 1))  # diferencia por fila

   A  B  C  D
0  6  8  5  3
1  4  5  4  9
2  6  7  7  0

0    5
1    5
2    7
dtype: int32

## 3 Estadística descriptiva

- Análisis preliminar de los datos
- Para Series y DataFrame

| Operación | Descripción |
|---|---|
| `count` | Número de valores no NaN |
| `describe` | Conjunto de estadísticas sumarias |
| `min`, `max` | Valores mínimo y máximo |
| `argmin`, `argmax` | Índices posicionales del valor mínimo y máximo |
| `idxmin`, `idxmax` | Índices semánticos del valor mínimo y máximo |
| `sum` | Suma de los elementos |
| `mean` | Media de los elementos |
| `median` | Mediana de los elementos |
| `mad` | Desviación absoluta media del valor medio |
| `var` | Varianza de los elementos |
| `std` | Desviación estándar de los elementos |
| `cumsum` | Suma acumulada de los elementos |
| `diff` | Diferencia aritmética de los elementos |

In [29]:
diccionario = { "nombre" : ["Marisa","Laura","Manuel", "Carlos"],
                "edad" : [34,34,11, 30],
                "puntos" : [98,12,98,np.nan],
                "genero": ["F", "F", "M", "M"] }
frame = pd.DataFrame(diccionario)
display(frame)
display(frame.describe())  # datos generales de elementos

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

In [30]:
# operadores básicos
print(frame.sum())
display(frame)
print(frame.sum(axis=1, numeric_only=True))

nombre    MarisaLauraManuelCarlos
edad                          109
puntos                      208.0
genero                       FFMM
dtype: object

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

0    132.0
1     46.0
2    109.0
3     30.0
dtype: float64

In [31]:
frame.mean(numeric_only=True)

edad      27.250000
puntos    69.333333
dtype: float64

In [32]:
frame.cumsum()

                    nombre  edad  puntos genero
0                   Marisa    34    98.0      F
1              MarisaLaura    68   110.0     FF
2        MarisaLauraManuel    79   208.0    FFM
3  MarisaLauraManuelCarlos   109     NaN   FFMM

In [33]:
frame.count(axis=1)

0    4
1    4
2    4
3    3
dtype: int64

In [34]:
print(frame['edad'].std())

10.996211468804457

In [35]:
frame['edad'].idxmax()

0

In [36]:
frame['puntos'].idxmin()

1

In [37]:
# frame con las filas con los valores maximos de una columna
print(frame['puntos'].max())

display(frame[frame['puntos'] == frame['puntos'].max()])

98.0

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

In [38]:
frame["ranking"] = frame["puntos"].rank(method='max')

In [39]:
display(frame)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

## Agregaciones

In [40]:
display(frame)
df = frame.groupby('genero').count()
display(df)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

        nombre  edad  puntos  ranking
genero
F            2     2       2        2
M            2     2       1        1

In [41]:
# si es NaN descarta la fila
df = frame.groupby('puntos').count()
display(df)

        nombre  edad  genero  ranking
puntos
12.0         1     1       1        1
98.0         2     2       2        2

In [42]:
display(frame.groupby('genero').mean(numeric_only=True))

        edad  puntos  ranking
genero
F       34.0    55.0      2.0
M       20.5    98.0      3.0

In [43]:
display(frame.groupby('genero').max())

        nombre  edad  puntos  ranking
genero
F       Marisa    34    98.0      3.0
M       Manuel    30    98.0      3.0

In [44]:
# funciones de agregación de varias columnas para obtener distintos estadísticos
display(frame.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max']))

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

In [45]:
# Filtrado de los datos en el que el conjunto no supera una media determinada
def media(x):
    return x["edad"].mean() > 30

display(frame)
frame.groupby('genero').filter(media)

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0
2  Manuel    11    98.0      M      3.0
3  Carlos    30     NaN      M      NaN

   nombre  edad  puntos genero  ranking
0  Marisa    34    98.0      F      3.0
1   Laura    34    12.0      F      1.0

## Correlaciones

pandas incluye métodos para analizar correlaciones - relación matemática entre dos variables (-1 negativamente relacionadas, 1 positivamente relacionadas, 0 sin relación).

- `obj.corr(obj2)` --> medida de correlación entre los datos de ambos objetos
- Más información: https://blogs.oracle.com/ai-and-datascience/post/introduction-to-correlation

### Ejemplo Fuel efficiency

- https://archive.ics.uci.edu/ml/datasets/Auto+MPG

In [46]:
import pandas as pd

path = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(path, sep=r'\s+', header=None,
                        names = ['mpg', 'cilindros', 'desplazamiento','potencia',
                                 'peso', 'aceleracion', 'año', 'origen', 'nombre'],
                        na_values='?', engine='c')

In [47]:
display(mpg_data.sample(5))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
253,20.5,6,200.0,95.0,3155.0,18.2,78,1,chevrolet malibu
50,28.0,4,116.0,90.0,2123.0,14.0,71,2,opel 1900
320,37.0,4,119.0,92.0,2434.0,15.0,80,3,datsun 510 hatchback
95,12.0,8,455.0,225.0,4951.0,11.0,73,1,buick electra 225 custom
225,17.5,6,250.0,110.0,3520.0,16.4,77,1,chevrolet concours

In [48]:
display(mpg_data.describe(include='all'))

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
count,398.000000,398.000000,398.000000,392.000000,398.000000,398.000000,398.000000,398.000000,398
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ford pinto
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
mean,23.514573,5.454774,193.425879,104.469388,2970.424623,15.568090,76.010050,1.572864,NaN
std,7.815984,1.701004,104.269838,38.491160,846.841774,2.757689,3.697627,0.802055,NaN
min,9.000000,3.000000,68.000000,46.000000,1613.000000,8.000000,70.000000,1.000000,NaN
25%,17.500000,4.000000,104.250000,75.000000,2223.750000,13.825000,73.000000,1.000000,NaN
50%,23.000000,4.000000,148.500000,93.500000,2803.500000,15.500000,76.000000,1.000000,NaN
75%,29.000000,8.000000,262.000000,126.000000,3608.000000,17.175000,79.000000,2.000000,NaN
max,46.600000,8.000000,455.000000,230.000000,5140.000000,24.800000,82.000000,3.000000,NaN

In [49]:
mpg_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   mpg             398 non-null    float64
 1   cilindros       398 non-null    int64
 2   desplazamiento  398 non-null    float64
 3   potencia        392 non-null    float64
 4   peso            398 non-null    float64
 5   aceleracion     398 non-null    float64
 6   año             398 non-null    int64
 7   origen          398 non-null    int64
 8   nombre          398 non-null    str
dtypes: float64(5), int64(3), str(1)
memory usage: 28.1 KB

### Correlaciones entre valores

In [50]:
mpg_data['mpg'].corr(mpg_data['peso'])  # + mpg = - peso

np.float64(-0.8317409332443352)

In [51]:
mpg_data['peso'].corr(mpg_data['aceleracion'])  # + peso = - aceleracion

np.float64(-0.4174573199403932)

### Correlaciones entre todos los valores

In [52]:
mpg_data.corr(numeric_only=True)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289,0.579267,0.563450
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419,-0.348746,-0.562543
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684,-0.370164,-0.609409
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196,-0.416361,-0.455171
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457,-0.306564,-0.581024
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000,0.288137,0.205873
año,0.579267,-0.348746,-0.370164,-0.416361,-0.306564,0.288137,1.000000,0.180662
origen,0.563450,-0.562543,-0.609409,-0.455171,-0.581024,0.205873,0.180662,1.000000

In [53]:
#año y origen no parecen correlacionables
#eliminar columnas de la correlacion
corr_data = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
display(corr_data)

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

In [54]:
# representación gráfica matplotlib
import matplotlib.pyplot as plt

In [55]:
# representación gráfica
corr_data.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1)

In [56]:
# correlación más negativa
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmin()

mpg                   peso
cilindros              mpg
desplazamiento         mpg
potencia               mpg
peso                   mpg
aceleracion       potencia
dtype: str

In [57]:
# correlación más positiva
mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True).idxmax()  # consigo misma....

mpg                          mpg
cilindros              cilindros
desplazamiento    desplazamiento
potencia                potencia
peso                        peso
aceleracion          aceleracion
dtype: str

In [58]:
# tabla similar con las correlaciones más positivas (evitar parejas del mismo valor)
corr_matrix = mpg_data.drop(['año','origen'],axis=1).corr(numeric_only=True)
# .to_numpy(copy=True) asegura un array modificable (evita ValueError: read-only en pandas recientes)
arr = corr_matrix.to_numpy(copy=True)
np.fill_diagonal(arr, 0)
positive_corr = pd.DataFrame(arr, index=corr_matrix.index, columns=corr_matrix.columns)
display(positive_corr)
positive_corr.idxmax()

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,0.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,0.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,0.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,0.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,0.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,0.000000

mpg                  aceleracion
cilindros         desplazamiento
desplazamiento         cilindros
potencia          desplazamiento
peso              desplazamiento
aceleracion                  mpg
dtype: str

In [59]:
positive_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1, vmin=-1.0, vmax=1.0)

## Ejercicios

- Ejercicios para practicar Pandas: https://github.com/ajcr/100-pandas-puzzles/blob/master/100-pandas-puzzles.ipynb